name: pul_solr
services:
  blacklight_test_solr:
    type: solr:8.4
    portforward: true
    core: blacklight-core
    config:
      dir: solr_configs/catalog-production-v2/conf
  dss_test_solr:
    type: solr:8.4
    portforward: true
    core: blacklight-core
    config:
      dir: solr_configs/dss-production/conf
  pulmap_test_solr:
    type: solr:8.4
    portforward: true
    core: blacklight-core
    config:
      dir: solr_configs/pulmap/conf
proxy:
  blacklight_test_solr:
    - blacklight.test.solr.lndo.site:8983
  dss_test_solr:
    - dss.test.solr.lndo.site:8983
  pulmap_test_solr:
    - pulmap.test.solr.lndo.site:8983
