version: 2
jobs:
  build:
    working_directory: ~/pul_solr

    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - pul_solr-{{ checksum "Gemfile" }}
          - pul_solr-

      - run: gem install bundler -v '~> 2.0'

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --without development production --jobs 4 --retry 3

      - save_cache:
          key: pul_solr-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle

      - run:
          name: Start Solr test instance
          command: bundle exec rake solr:start
          background: true

      - run: bin/jetty_wait

      - run:
          name: Rspec
          command: bundle exec rspec spec
          environment:
            RAILS_ENV: test
