version: 2
jobs:
  build:
    working_directory: ~/pul_solr

    docker:
      - image: cimg/ruby:3.1.0
        environment:
          RAILS_ENV: test
      - image: pulibrary/ci-solr:8.4-v2.0.0
        command: server/scripts/ci-start.sh
    steps:
      - checkout

      - restore_cache:
          keys:
          - pul_solr-{{ checksum "Gemfile" }}
          - pul_solr-

      - run: gem install bundler

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --without development production --jobs 4 --retry 3

      - save_cache:
          key: pul_solr-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle

      - run:
          name: Load catalog configs into solr and create collection
          command: |
            cd solr_configs/catalog-production-v2/conf
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://solr:SolrRocks@localhost:8983/solr/admin/configs?action=UPLOAD&name=catalog"
            curl -H 'Content-type: application/json' "http://solr:SolrRocks@localhost:8983/api/collections/" -d '{create: {name: blacklight-core, config: catalog, numShards: 1}}'
      - run:
          name: Load pulmap configs into solr and create collection
          command: |
            cd solr_configs/pulmap/conf
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://solr:SolrRocks@localhost:8983/solr/admin/configs?action=UPLOAD&name=pulmap"
            curl -H 'Content-type: application/json' "http://solr:SolrRocks@localhost:8983/api/collections/" -d '{create: {name: pulmap-core, config: pulmap, numShards: 1}}'
      - run:
          name: Rspec
          command: bundle exec rspec spec
          environment:
            RAILS_ENV: test
