---
solr8_production:
  - 'cdh_shxco'
  - 'dpul-production'
  - 'dss-production2'
  - 'pulfalight-production'
  - 'cicognara'
  - 'lae'
  - 'catalog-alma-production3'
  - 'catalog-alma-production2'
  - 'pdc-discovery-production1'
  - 'pdc-discovery-production2'
  - 'oawaiver-production'
  - 'figgy-production'
  - 'pulmap'
  - 'library-prod1' # uses libwww configset, which is the same as solr 7
  - 'special-collections-prod2' # uses libwww configset, which is the same as solr 7
solr8_staging:
  - 'catalog-qa1' # uses catalog v2 production configset
  - 'catalog-qa2' # uses catalog v2 production configset
  - 'catalog-staging1' # uses catalog v2 production configset
  - 'catalog-staging2' # uses catalog v2 production configset
  - 'cdh_shxco'
  - 'dss-staging1' # uses dss production configset
  - 'pulfalight-staging'
  - 'pulfalight-qa' # uses pulfalight-staging configset
  - 'cicognara-staging'
  - 'lae-staging'
  - 'dpul-staging'
  - 'pdc-discovery-staging'
  - 'oawaiver-staging'
  - 'figgy-staging'
  - 'pulmap-staging'
  - 'library-staging1' # uses libwww configset, which is the same as solr 7
  - 'special-collections-staging1' # uses libwww configset, which is the same as solr 7
solr9_production:
  - 'cdh_ppa'
  - 'geniza'
solr9_staging:
  - 'cdh_ppa'
  - 'geniza'
