---
solr8_production:
  - 'catalog-production1'
  - 'catalog-production2'
  - 'dss-production' # uses catalog-production config set
  - 'pulfalight-production'
  - 'cicognara'
  - 'lae'
  - 'catalog-alma-production3'
  - 'catalog-alma-production2'
  - 'pdc-discovery-production'
  - 'oawaiver-production'
solr8_staging:
  - 'catalog-staging'
  - 'catalog-alma-staging1' # uses catalog staging configset
  - 'catalog-alma-staging2' # uses catalog staging configset
  - 'dss-staging' # uses catalog configset
  - 'pulfalight-staging'
  - 'cicognara-staging'
  - 'lae-staging'
  - 'dpul-staging'
  - 'pdc-discovery-staging'
  - 'oawaiver-staging'
  - 'figgy-staging'
solr7_staging:
  - 'figgy-staging'
  - 'libsc-staging'
  - 'pulmap-staging'
solr7_production:
  - 'dpul-production'
  - 'figgy-production1'
  - 'pulmap'
