---
solr8_production:
  - 'catalog-production1'
  - 'catalog-production2'
  - 'dss-production' # uses catalog-production config set
  - 'pulfalight-production'
  - 'cicognara'
  - 'lae'
  - 'catalog-alma-production1'
  - 'catalog-alma-production2'
solr8_staging:
  - 'catalog-alma-qa' # uses catalog staging configset
  - 'catalog-staging'
  - 'dss-staging' # uses catalog configset
  - 'pulfalight-staging'
  - 'cicognara-staging'
  - 'lae-staging'
solr7_staging:
  - 'dpul-staging'
  - 'figgy'
  - 'libsc-staging'
  - 'libwww-production'
  - 'libwww-staging'
  - 'pulmap-staging'
solr7_production:
  - 'cicognara'
  - 'dpul-production'
  - 'figgy-production1'
  - 'lae'
  - 'pulmap'
